#!/bin/sh
set -eu
PROFILES=/config/nginx/profile
TEMPORARY="/dev/shm/template.tmp"

cleanup() {
  local rc=$?
  if [ -f "${TEMPORARY}" ]; then
    rm -- "${TEMPORARY}" || true
  fi
  exit "${rc}"
}

trap cleanup EXIT

show_vars() {
local selected="${1}"
  if [ ! -f "${PROFILES}/${selected}" ]; then
    printf -- "template-engine: profile %s not found ...\n" "${selected}"
    exit 1
  fi
  printf -- "%-30.30s %-30.30s %s\n" "KEY" "DEFAULT" "VALUE"
  printf -- "--------------------------------------------------------------------\n"
  printf -- "%-30.30s %-30.30s %s\n" "LISTEN" "8080" "${LISTEN-8080}"
  grep -E '^#::[A-Z_]+=.+$' "${PROFILES}/${selected}" | cut -c 4- | while read template; do
    key="$(echo -n "${template}" | awk -F= '{print $1}')"
    val="$(echo -n "${template}" | awk -F= '{print $2}')"
    config_key="\${CONFIG_${key}}"
    config_key_set="\${CONFIG_${key}+set}"
    eval "config_set=${config_key_set}"
    if [ -n "${config_set}" ]; then
      eval "config=${config_key}"
    else
     config="${val}"
    fi
    printf -- "%-30.30s %-30.30s %s\n" "${key}" "${val}" "${config}"
  done
}

if [ -n "${1-}" ]; then
  SELECTED="$1"
elif [ -n "${PROFILE-}" ]; then
  SELECTED="vars:${PROFILE}"
else
  exit 200
fi

if [ "${SELECTED:0:5}" == "vars:" ]; then
  show_vars "${SELECTED:5}"
  exit 0
fi

[ -f "${PROFILES}/${SELECTED}" ] || exit 1
TEMPLATE="${PROFILES}/${SELECTED}"

grep -v -E '^#::[A-Z_]+=.+$' "${TEMPLATE}" >"${TEMPORARY}"

grep -E '^#::[A-Z_]+=.+$' "${TEMPLATE}" | cut -c 4- | while read template; do
  key="$(echo -n "${template}" | awk -F= '{print $1}')"
  val="$(echo -n "${template}" | awk -F= '{print $2}')"
  config_key="\${CONFIG_${key}}"
  config_key_set="\${CONFIG_${key}+set}"
  eval "config_set=${config_key_set}"
  if [ -n "${config_set}" ]; then
    eval "config=${config_key}"
  else
   config="${val}"
  fi
  config="${config//\//\\/}"
  sed -i -e "s/{{${key}}}/${config}/g" "${TEMPORARY}"
done
sed -i -e "s/{{LISTEN}}/${LISTEN-8080}/g" "${TEMPORARY}"
if [ -n "${2-}" ]; then
  mv -f -- "${TEMPORARY}" "${2}"
fi
